SELECT * FROM FOOD;

SELECT * FROM FOOD WHERE ISVEGAN = TRUE;

SELECT * FROM FOOD order BY PRICE;

SELECT CALORIES, ISVEGAN, NAME, max(PRICE) AS PRICE, NAME FROM FOOD;

SELECT MENU_ID, COUNT(*) AS NUMBER_OF_FOOD FROM MENU_FOOD GROUP BY MENU_ID;

SELECT R.ID AS RESTAURANT_ID, R.NAME, A.CITY, A.COUNTRY, A.STREET, A.ZIPCODE
FROM RESTAURANT R, ADDRESS A 
WHERE R.ID = A.ID;

SELECT * FROM MENU_FOOD MF JOIN FOOD F ON MF.FOODS_ID = F.ID 
JOIN MENU M ON M.ID = MF.MENU_ID
WHERE curdate() BETWEEN FROMDATE AND TODATE;


