INSERT INTO FOOD (CALORIES, ISVEGAN, NAME, PRICE) values(100, false, "gulyas", 890);
INSERT INTO FOOD (CALORIES, ISVEGAN, NAME, PRICE) values(50, true, "tofu", 1500);
INSERT INTO FOOD (CALORIES, ISVEGAN, NAME, PRICE) values(1500, false, "csirkepaprikas", 2200);
INSERT INTO FOOD (CALORIES, ISVEGAN, NAME, PRICE) values(100, true, "gyumolcstal", 1200);
INSERT INTO FOOD (CALORIES, ISVEGAN, NAME, PRICE) values(800, true, "szilvasgomboc", 1150);

INSERT INTO ADDRESS (CITY, COUNTRY, STREET, ZIPCODE) VALUES ("Budapest", "Magyarorszag", "Futo", 1082);

INSERT INTO RESTAURANT(NAME, ADDRESS_ID) VALUES ("10 MINUTES", 1);

INSERT INTO MENU(RESTAURANT_ID, FROMDATE, TODATE) VALUES (1, curdate(), curdate() + interval 1 month - interval 1 day);
INSERT INTO MENU(RESTAURANT_ID, FROMDATE, TODATE) VALUES (1, curdate() + interval 1 month, curdate() + interval 2 month - interval 1 day);

INSERT INTO FOOD (CALORIES, ISVEGAN, NAME, PRICE) values(2000, false, "sztrapacska", 1800);
INSERT INTO FOOD (CALORIES, ISVEGAN, NAME, PRICE) values(1000, true, "lekvaros palacsinta", 150);

INSERT INTO MENU_FOOD(MENU_ID, FOODS_ID) VALUES (1, 1);
INSERT INTO MENU_FOOD(MENU_ID, FOODS_ID) VALUES (1, 2);
INSERT INTO MENU_FOOD(MENU_ID, FOODS_ID) VALUES (1, 3);
INSERT INTO MENU_FOOD(MENU_ID, FOODS_ID) VALUES (1, 4);
INSERT INTO MENU_FOOD(MENU_ID, FOODS_ID) VALUES (1, 5);
INSERT INTO MENU_FOOD(MENU_ID, FOODS_ID) VALUES (2, 6);
INSERT INTO MENU_FOOD(MENU_ID, FOODS_ID) VALUES (2, 7);
