CREATE TABLE FOOD(
ID INT(10) NOT NULL,
CALORIES INT(10) NULL,
ISVEGAN BIT(1) NOT NULL,
NAME VARCHAR(255) NOT NULL,
PRICE INT(10) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE ADDRESS(
ID INT(10) NOT NULL,
CITY VARCHAR(255) NOT NULL,
COUNTRY VARCHAR(255) NOT NULL,
STREET VARCHAR(255) NOT NULL,
ZIPCODE VARCHAR(255) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE RESTAURANT(
ID INT(10) NOT NULL,
NAME VARCHAR(255) NOT NULL,
ADDRESS_ID INT(10) NULL,
PRIMARY KEY(ID),
FOREIGN KEY(ADDRESS_ID) references ADDRESS(ID)
);

CREATE table MENU(
ID int(10) NOT null,
RESTAURANT_ID int(10) NOT NULL,
FROMDATE date NULL,
TODATE date NULL,
PRIMARY KEY (ID),
FOREIGN KEY (RESTAURANT_ID) references RESTAURANT(ID) 
);

CREATE TABLE MENU_FOOD(
MENU_ID INT(10) NOT NULL,
FOODS_ID INT(10) NOT NULL,
PRIMARY KEY(MENU_ID, FOODS_ID),
FOREIGN KEY(MENU_ID) references MENU(ID),
FOREIGN KEY(FOODS_ID) REFERENCES FOOD(ID)
);